version: "3"
services:
  <%= NAME.toLowerCase() %>-app:
    image: <%= NAME.toLowerCase() %>
    environment:
      - SPRING_PROFILES_ACTIVE=prod<% if (RDBMS === 'Mysql') { %>
      - SPRING_DATASOURCE_URL=jdbc:mysql://<%= NAME.toLowerCase() %>-mysql:3306/<%= NAME.toLowerCase() %>db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=<% } %><% if (ELASTICSEARCH) { %>
      - APPLICATION_ELASTICSEARCH_TARGETURI=elasticsearch://<%= NAME.toLowerCase() %>-elasticsearch:9200<% } %>
    ports:
      - 8080:8080<% if (RDBMS === 'Mysql') { %>
  <%= NAME.toLowerCase() %>-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=<%= NAME.toLowerCase() %>db
    ports:
      - 3306:3306<% } %><% if (ELASTICSEARCH) { %>
  <%= NAME.toLowerCase() %>-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command:
      - elasticsearch
      - -Etransport.host=0.0.0.0
    ports:
      - 9200:9200<% } %>
