application:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers:
    allow-credentials: true
    max-age: 1800<% if (ELASTICSEARCH) { %>
  elasticsearch:
    targetUri: elasticsearch://localhost:9300
    clusterName: elasticsearch<% } %>

<% if (AUTH === 'JWT') { %>jwt:
  secretKey: secret-key-changeit
  expirationTime: 864000000<% } %>

<% if (RDBMS !== 'None') { %>spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<%= NAME %>db
    username: <%= NAME %>
    password: <%= NAME %>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

liquibase:
  change-log: classpath:liquibase/master.xml
<% } %>
